export const SET_BANNERS = 'SET_BANNERS';

export const SET_QUICKNAV = 'SET_QUICKNAV';

export const SET_CUSTOMS = 'SET_CUSTOMS';

export const SET_GOODSLIST = 'SET_GOODSLIST';

export const SET_GOODSINFO = 'SET_GOODSINFO';

export const SET_MENULIST = 'SET_MENULIST';

export const SET_CATEGORYLIST = 'SET_CATEGORYLIST';

export const SET_CARTLIST = 'SET_CARTLIST';

export const SET_SELECT_GOOD = 'SET_SELECT_GOOD';

export const SET_SELECT_SHOP = 'SET_SELECT_SHOP';

export const SET_SELECT_CART_ALL = 'SET_SELECT_CART_ALL';

export const SET_BUY_QUANTITY = 'SET_BUY_QUANTITY';

export const SET_BUY_EDIT_STATUS = 'SET_BUY_EDIT_STATUS';

export const DEL_CART_GOOD = 'DEL_CART_GOOD';
